name: Docker Image Build, Test & Deploy

on:
  push:
    branches: [ php-7.4.19-rhel-8 ]
  pull_request:
    branches: [ php-7.4.19-rhel-8 ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3